### ISSUE TITLE
Versión tablet

### ISSUE THREAD

**Issue by nasivuela** [Adalab/d-s1-evaluacion-intermedia-ElisabetAS#8]
Cuando tengamos cerrados el resto de issues, a darle caña a ese responsive!

![](https://media.giphy.com/media/rMTjczTpDF2I8/giphy.gif)

**Comment by ElisabetAS** [comment]
No encuentro la carpeta de la evaluación donde estaba el diseño de tablet!!! Se me ha perdido! Cómo hago el responsive???

**Comment by ElisabetAS** [comment]
Ya lo he encontrado, gracias :smile:
