### ISSUE TITLE
Arreglar orden de css <links> en <head>

### ISSUE THREAD

**Issue by nasivuela** [Adalab/d-s1-evaluacion-intermedia-ElisabetAS#9]
Buen trabajo @ElisabetAS !

¿Ajustamos un detallico y le ponemos la guinda?

Parece que estamos intentado utilizar la fuente Rubik en nuestro css cuando todavía no la ha descargado la página. Igual si cambiamos el orden de esas etiquetas `link` la cosa se apaña ;)

![](https://media.giphy.com/media/OAd8SBimLJXOM/giphy.gif)

**Comment by ElisabetAS** [comment]
No te entiendo :confused:

**Comment by nasivuela** [comment]
En el HTML el link de tu css está antes que el link de la fuente, si no lo ves claro luego te cuento

**Comment by ElisabetAS** [comment]
Ya te he entendido creo! Ya está resuelto, creo también!
